using Autodesk.Revit.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace generalsolution.revitplugin
{
    public class elements
    {
        public int id { get; set; }
        public string name { get; set; }
        //public List<Element>GetElements()
        //{

        //    return;
        //        //new List<Element>() { new Element() {Id= 1,Name= "A"}, 
        //        //    new Element() { Id = 1, Name = "A" }
                
                
        //        }
        }
    }

